name = "Shalom Olam"
license = "GPLv3.0"
licenselink = "https://github.com/LKummer/shalom-olam-hugo-theme/blob/master/LICENSE"
description = "The first Hebrew Hugo theme."
homepage = "https://github.com/LKummer/shalom-olam-hugo-theme/"
tags = []
features = [
  "Left To Right",
  "Responsive",
  "SEO",
  "Fuzzy Search",
  "IE11 Compatibility"
]
min_version = "0.41"

[author]
  name = "Lior Kummer"
  homepage = "https://github.com/LKummer"